#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MathPro.Resource", IsApplication=true)]

namespace MathPro
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int A = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ApplicationIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ArrowDown = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ArrowLeft = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ArrowRight = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ArrowUp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int B = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int boarder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int C = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cartesian_plane = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cartesian_plane_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chalkboard = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int closeBrace = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int closeBraceSquare = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cos = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cosec = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cot = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Cursor = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int D = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int deleteIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int divide = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int E = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Eight = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int equal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int F = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Five = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Four = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int G = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int greaterOrEqual = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int greaterthan = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int H = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int help_1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int help_2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int help_3 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int help_4 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int help_5 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int help_6 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int help_7 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int help_8 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int help_9 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int help_left = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int help_right = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int I = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int J = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int K = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int L = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Line = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Log = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int LongDivision = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int M = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int minus = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int multiply = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int N = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Nine = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int O = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int One = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int openBrace = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int openBraceSquare = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int or = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int P = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int plus = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int plusMinus = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Q = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int R = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int root = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int S = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int sec = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Seven = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int sin = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Six = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int SmallerOrEqual = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int smallerthan = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int splashscreenimage = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int T = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int tan = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int termMultiply = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Three = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int Triangle = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int TriangleNintyAngle = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int Two = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int U = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int undo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int V = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int W = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int X = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int Zero = 2130837591;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002e
			public const int btnAddTransformation = 2131099694;
			
			// aapt resource value: 0x7f060005
			public const int btnBasic = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int btnDistribute = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int btnExponential = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int btnFactor = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int btnGraphEquation = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int btnGraphParabola = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int btnGraphStraight = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int btnInequalities = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int btnLogarithmic = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int btnMainEquaions = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int btnMainGeometry = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int btnMainGraphs = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int btnMainHelp = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnMainSettings = 2131099675;
			
			// aapt resource value: 0x7f060009
			public const int btnPlotGeoShape = 2131099657;
			
			// aapt resource value: 0x7f06001d
			public const int btnPlotShapeGeoPage = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int btnSimplify = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int btnSolve = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int btnTransformationGeometry = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int help_count = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int help_demo = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int help_image = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int help_left = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int help_right = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int hostess = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int hostessPlotGeo = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int myButton = 2131099668;
			
			// aapt resource value: 0x7f060029
			public const int panelEnlargement = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int panelReflection = 2131099684;
			
			// aapt resource value: 0x7f060028
			public const int panelRotation = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int panelTranslation = 2131099691;
			
			// aapt resource value: 0x7f060023
			public const int rdEnlargement = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int rdReflection = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int rdRotation = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int rdTranslation = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int rdXAxis = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int rdXequalsY = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int rdYAxis = 2131099686;
			
			// aapt resource value: 0x7f06001e
			public const int spinnerInitialLoad = 2131099678;
			
			// aapt resource value: 0x7f06000e
			public const int surface = 2131099662;
			
			// aapt resource value: 0x7f06001f
			public const int txtAdded = 2131099679;
			
			// aapt resource value: 0x7f06002a
			public const int txtEnlargement = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int txtHorizontal = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int txtVertical = 2131099692;
			
			// aapt resource value: 0x7f060015
			public const int zoomIn = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int zoomOut = 2131099670;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Algebra_Menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Equations_Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Geometry_Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Graphs_Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Graphs_View = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int help_screen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main_Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Player = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PlotGeoShape = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int setting_screen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SplashView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Straight_line = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Transformation_Geo = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
